### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by rogerbten** [artf/grapesjs-plugin-ckeditor#1]
I'm using the CKEditor plugin with newsletter editor, when choosing the font type, the listing does not overlap in the div.
Tks.
![screen shot 2017-04-18 at 3 35 13 pm](https://cloud.githubusercontent.com/assets/27738801/25147433/e51d0d5e-244d-11e7-9adb-15e045ac8d0f.png)

**Comment by artf** [comment]
It was just because I've used `overflow: hidden` on the toolbar element but I've fixed it in the last release (v0.5.1), so just try to update grapesjs (js and css) and refresh (make sure css is not cached)

**Comment by rogerbten** [comment]
I updated css and js (v0.5.1), CKEditor is ok. But the publisher ran out of icons.
![screen shot 2017-04-18 at 6 11 19 pm](https://cloud.githubusercontent.com/assets/27738801/25153545/4885cb64-2463-11e7-9c76-da3a293a67e4.png)

**Comment by artf** [comment]
About Blocks style I got where is the problem but the one with icons it's strange. Can you inspect and see if there are errors in console? Seems just like it's unable to load fonts

**Comment by rogerbten** [comment]
I cleared the browser cache, no error is appearing on the console.
![screen shot 2017-04-18 at 8 49 20 pm](https://cloud.githubusercontent.com/assets/27738801/25157671/2cb8dfc8-2479-11e7-8f6e-ccae37817795.png)

**Comment by artf** [comment]
Hi @rogerbten I updated the style for the newsletter preset. About fonts, can't reproduce it.
Make sure the font from FontAwesome is correctly loaded and the style is correctly added.
![font-loaded](https://cloud.githubusercontent.com/assets/11614725/25206478/7902ad06-2568-11e7-9cff-6c2f2041c03c.png)

![class-loaded](https://cloud.githubusercontent.com/assets/11614725/25206472/726d2caa-2568-11e7-83db-14ac211cd2f7.png)

**Comment by rogerbten** [comment]
@artf , I updated the style for the newsletter preset , working perfectly !! Without words, thank you.
One question, is there a possibility to change the language?

![screen shot 2017-04-19 at 11 39 43 pm](https://cloud.githubusercontent.com/assets/27738801/25211194/5f542a6e-255a-11e7-9ea3-45ba693e02fc.png)

**Comment by artf** [comment]
Glad you solved :)
About the language, I don't plan anything and [here](https://github.com/artf/grapesjs/issues/26) I've  explained why
