### ISSUE TITLE
position of link button ckeditor grapesjs

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-plugin-ckeditor#10]
ckeditor in grapesjs is not maintaining its position when we click on the ok button link dialog box. it always go to the starting position. Urgently help needed and fixing.
Thanks.
![33421947-af1072ac-d5d5-11e7-8d70-aecffc6e0ecb](https://user-images.githubusercontent.com/33541046/33524255-d7946276-d83a-11e7-8436-9b986cca477d.png)

**Comment by artf** [comment]
Should be fixed with the latest release https://github.com/artf/grapesjs-plugin-ckeditor/releases/tag/v0.0.9
