### ISSUE TITLE
span elements are not editable

### ISSUE THREAD

**Issue by effectief** [artf/grapesjs-plugin-ckeditor#12]
I want to apply a tags having a class to content. 

So I add the styles to styles.js

ckeditor\styles.js:
{ name: 'Big',		element: 'span', attributes: { 'class': 'Big' } },
{ name: 'Medium',		element: 'span', attributes: { 'class': 'Medium' } },
{ name: 'Small',		element: 'span', attributes: { 'class': 'Small' } },

This works fine, but when I saved the content and reload the page, it went wrong when I click again on the text with the class. I got the next error:

grapes.min.js:2 Error: The specified element mode is not supported on element: "span".
    at new a (ckeditor.js:260)
    at Object.CKEDITOR.inline (ckeditor.js:344)
    at Object.enable (grapesjs-plugin-ckeditor.min.js:2)
    at Object.enable (grapes.min.js:11)
    at i.enableEditing (grapes.min.js:2)

enableEditing: function() {
                var t = this.rte;
                if (!this.rteEnabled && this.model.get("editable")) {
                    if (t)
                        try {
                            this.activeRte = t.enable(this, this.activeRte)
                        } catch (t) {
                            **console.error(t)**
                        }
                    this.rteEnabled = 1,
                    this.toggleEvents(1)
                }
            },

How can we fix this?

**Comment by artf** [comment]
there is an option to enable in CKEditor
https://stackoverflow.com/questions/14575036/enable-ckeditor4-inline-on-span-and-other-inline-tags
