### ISSUE TITLE
Pressing enter jumps the user down the page

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs-plugin-ckeditor#13]
While editing the content within a text component, whenever a user presses the enter key, the user gets jumped further down the page. I'm unable to reproduce this in the demo, which makes me think perhaps there's an issue that's causing the newest CKEditor version and Grapes to not play well together?

My configuration:
```	plugins: ['gjs-plugin-ckeditor'],
	pluginsOpts: {
		'gjs-plugin-ckeditor': {
			position: 'center',
			options: {
				customConfig: '',
				language: 'en',
				
				startupFocus: true,
				extraAllowedContent: '*(*);*{*}', // Allows any class and any inline style
				allowedContent: true, // Disable auto-formatting, class removing, etc.
				enterMode: CKEDITOR.ENTER_BR,
				extraPlugins: 'sharedspace,justify,colorbutton,panelbutton,font',
				toolbar: [
					{ name: 'styles', items: ['Font', 'FontSize' ] },
					['Bold', 'Italic', 'Underline', 'Strike'],
					{name: 'paragraph', items : [ 'NumberedList', 'BulletedList']},
					{name: 'links', items: ['Link', 'Unlink']},
					{name: 'colors', items: [ 'TextColor', 'BGColor' ]},
				],
			},
		},
	},```

**Comment by artf** [comment]
To be honest I've faced [this issue](https://github.com/artf/grapesjs/blob/dev/src/canvas/view/CanvasView.js#L116-L122) already but not able to reproduce on the current demo  🤔
BTW try to add this to your canvasCss and see if it solves the issue
```js
grapesjs.init({
	canvasCss: 'body {height: auto;}',
	....
})
```

**Comment by AustinTBiggs** [comment]
@artf  - That works perfectly! Even in Firefox
