### ISSUE TITLE
Bind CKEDITOR on one div having an named class (instead of all P tags)

### ISSUE THREAD

**Issue by oakk90** [artf/grapesjs-plugin-ckeditor#15]
The CKEDITOR is bind on each P element. Is it possible to bind CKEDITOR on an div having an class?

Mine situation:

`<div class="Content"><p>Hello <span class="bold">world</span></p><p>Working with <span class="bold">CKEDITOR</span></p></div>`

**Comment by artf** [comment]
CKEditor is attached on TextComponents so you can explicitly indicate what is a text component for the editor, check this one #2
