### ISSUE TITLE
Can't figure out how to enable Bullet and Numbered list buttons in CKEditor

### ISSUE THREAD

**Issue by arblackman** [artf/grapesjs-plugin-ckeditor#17]
I'm running this exact project directly out of the box, and simply can't figure out why the UL and OL buttons are hidden when I initiate editing.

I've tried both clearing and explicitly setting the toolbar/toolbarGroups config and neither works.

Any ideas ?

**Comment by artf** [comment]
Check this one https://ckeditor.com/old/forums/CKEditor/Solved-CKEditor-not-displaying-NumberedList-button-or-numbered-lists-in-the-editor
