### ISSUE TITLE
overlay menu tool ckeditor if change height edited block

### ISSUE THREAD

**Issue by MuTaToR08** [artf/grapesjs-plugin-ckeditor#18]
Add text box and start typing text in 3 strings
![bug](https://user-images.githubusercontent.com/8342939/39771585-74731c50-52fb-11e8-85ce-8746af43adf5.png)

**Comment by MuTaToR08** [comment]
@artf please help

**Comment by xamdam777** [comment]
Maybe you can play with this https://stackoverflow.com/questions/16283597/move-the-ckeditor-inline-toolbar

**Comment by MuTaToR08** [comment]
@xamdam777  this is static offset,
My problem is that when the block is changed, the tooltip does not shift.

**Comment by artf** [comment]
The core RTE module is affected as well, so I created a new issue on the main repo. I close this, subscribe there to get notified when is done.
