### ISSUE TITLE
How to customize the Ckeditor

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs-plugin-ckeditor#19]
Hi @artf,

Hope you are doing fine.
Can you please let us know to customize the provided ckEditor plugin as we want to add more option on link popup of ckEditor.

Please let us do this.
Thanks in Advance.Doing great job with GrapesJS.

**Comment by artf** [comment]
@Deepak813 all you need is here https://github.com/artf/grapesjs-plugin-ckeditor/blob/master/README.md just read it carefully

**Comment by sunhillbd** [comment]
I tried to add the color picker and the text align into the ckeditor by following the guide. But these are not showing in the toolbar. Any suggestion? thanks @artf
