### ISSUE TITLE
Initialization ckeditor

### ISSUE THREAD

**Issue by rogerbten** [artf/grapesjs-plugin-ckeditor#2]
@artf , Hi... I set an html to initialize with the editor, but it is accusing an error when trying to format the text with the ckeditor.

Template html:
.....

```
<table class="footer" style="font-size:14px">
              <tr>
                <td>
                      <span>Oferta válida até o dia 24/05/2017, às 23h59 (horário de Brasília), para as compras efetuadas pela 
                      Internet, ou enquanto durarem nossos estoques (o que ocorrer primeiro).
                      </span>
                      <br><br>
                      <span>&nbsp;*MONTAGEM GRÁTIS.&nbsp;</span>
                      <a href="http://www.koerich.com.br/institucional/montagem" target="_blank">Consulte o regulamento</a>
                      <br><br>
                      <span>Caso tenha alguma dúvida, consulte o link &quot;</span>
                      <a href="http://www.koerich.com.br/institucional/atendimento" target="_blank">Atendimento</a>
                      <span>&quot; de nosso site.</span>
                </td>
              </tr>
            </table>

```

...

![screen shot 2017-05-23 at 5 27 24 pm](https://cloud.githubusercontent.com/assets/27738801/26375879/e7fe457a-3fe0-11e7-9fbc-59f2ceae0399.png)

**Comment by artf** [comment]
GrapesJS can't figure it out by itself when you expect to start the Text Component so it's just trying "somehow" to guess it. In this case, it treats those `<span>`s as individual Text Component (the error is thrown by CKEditor just because it doesn't like to launch the editor on tags as `<span>`, `<a>`, etc.) but I think in your case you just want a single text component. You might help GrapesJS parsing with this trick:
```html
<td>
  <!-- Let the editor know about the Text Component -->
  <div data-gjs-type="text">
    ... 
   <span> Oferta válida até o ... </span>
    ...
  </div>
</td>
```

**Comment by rogerbten** [comment]
@artf , It worked perfectly, thank you very much.  How can I use ckeditor to insert the link into the image? I would like to use this option, but the ckeditor is not initialized in the images.

**Comment by artf** [comment]
Did you try using 'Link Block' (available in demo)? You can add the link and then drop whatever you want (eg. images)

**Comment by rogerbten** [comment]
@artf , Yes, I did, but I did not find it very practical. Sometimes the layer of the image, due to overlapping it is bad to select the link block.

In my opinion, it is more practical you insert the image and in the properties insert a link ... my ideal would be something of the type the attachment
![screen shot 2017-05-24 at 8 51 37 pm](https://cloud.githubusercontent.com/assets/27738801/26430489/ffbdf366-40c3-11e7-954f-f5be79638807.png)

**Comment by artf** [comment]
Totally agree with you, but at the moment it's not possible, I have to create a new component for this purpose
