### ISSUE TITLE
How to customize toolbar?

### ISSUE THREAD

**Issue by krisnaw** [artf/grapesjs-plugin-ckeditor#24]
Any example of how to customize the toolbar?

This is my current code, but it is not working.

```
    pluginsOpts: {
        'gjs-plugin-ckeditor' : {
            language: 'en',
            toolbar: [
                { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
                { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
            ],
        }
    }
```

**Comment by AlessandroMagri** [comment]
Me too. Same situation. 
Now I'm using the config file from ckeditor to make it work...

**Comment by artf** [comment]
Not at the `'gjs-plugin-ckeditor'` level, but `'gjs-plugin-ckeditor'.options`
```js
pluginsOpts: {
        'gjs-plugin-ckeditor' : {
			options: {
            	language: 'en',
            	toolbar: [
                	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
                	{ name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
            	],
       	 	}
		}
    }
```

**Comment by dodyrosjidi** [comment]
how to show FontColor,FontSize and FontFamily from toolbar CKEditor?

**Comment by ko06** [comment]
any update on [this?](https://github.com/artf/grapesjs-plugin-ckeditor/issues/24#issuecomment-507695383)

**Comment by Hirokami** [comment]
> Not at the `'gjs-plugin-ckeditor'` level, but `'gjs-plugin-ckeditor'.options`
> 
> ```js
> pluginsOpts: {
>         'gjs-plugin-ckeditor' : {
> 			options: {
>             	language: 'en',
>             	toolbar: [
>                 	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
>                 	{ name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
>             	],
>        	 	}
> 		}
>     }
> ```

Hi. I've tried to setup the toolbar as described in the message, but nothing happened. Every editor has the default toolbar. I thought that how I import maybe matter, so I tried importing it from cdn directly into index.html, also tried to install it with npm. Always the same result. Some tips?

**Comment by artf** [comment]
Be sure to include the full CKEditor (which includes plugins), this is the configuration from the [demo](https://grapesjs.com/demo-newsletter-editor.html) and everything works as expected
![Schermata 2020-02-04 alle 21 05 13](https://user-images.githubusercontent.com/11614725/73782336-38aed280-4792-11ea-90ab-35161b75047e.png)

**Comment by vmagalhaes** [comment]
Why the 'Table' button inside the 'insert' group doesn't show up? Does anybody know?

**Comment by MortenSpjotvoll** [comment]
@artf 

I see you included 'Underline', 'NumberedList' and 'BulletedList' in your config, but these are missing from the demo. This can be solved by adding "options: { removeButtons: null }"

**Comment by riteshagarwalsw** [comment]
@artf The CL editor plugin works well, but when we **double click** text element, to open the RTE, the cursor position always starts at beginning of the text. What is the way to have the cursor position in between the text(where I did the double click)
Issue can be found in the demo link as well, [Demo](https://grapesjs.com/demo-newsletter-editor.html)
