### ISSUE TITLE
CKEditor tool bar is not displaying for Text blocks.

### ISSUE THREAD

**Issue by hemanthmc** [artf/grapesjs-plugin-ckeditor#25]
For the text-blocks it is allowing to display the CKEditor toolbar for the first time but once i save that template, then CKEditor toolbar is not displaying for Edited Text-blocks.

i am getting error as **`Error: The specified element mode is not supported on element: "u".`**

and i need to know where & How to configure 
CKEDITOR.dtd.$editable.span = 1; CKEDITOR.dtd.$editable.a = 1; CKEDITOR.dtd.$editable.strong = 1; CKEDITOR.disableAutoInline = true;

**Comment by artf** [comment]
> For the text-blocks it is allowing to display the CKEditor toolbar for the first time but once i save that template, then CKEditor toolbar is not displaying for Edited Text-blocks.

Read here please: https://grapesjs.com/docs/modules/Storage.html

> and i need to know where & How to configure

After loading the CKEDITOR script but before the editor initialization
