### ISSUE TITLE
Integrating with Reactjs

### ISSUE THREAD

**Issue by Amir2828** [artf/grapesjs-plugin-ckeditor#27]
Can anyone help regarding connecting the plugin to grapesjs through react?

been trying to connect through:

import CKEDITOR from 'ckeditor'
import grapesCK from 'grapesjs-plugin-ckeditor'

this.editor = grapesjs.init({
                plugins: [grapesCK],...

Everytime I try to double click on a text I get:
"TypeError: Cannot set property 'dir' of undefined"

Any help/thoughts will be appreciated

**Comment by umerrinayat** [comment]
Did you find any solution? @Amir2828

**Comment by Amir2828** [comment]
Yes, At the end I just used a CDN link in the index.html to CKEDITOR 4 and then continued like in the grapesjs guide
