### ISSUE TITLE
How to use this plugin in React?

### ISSUE THREAD

**Issue by ColdTuna** [artf/grapesjs-plugin-ckeditor#34]
I'm trying to use this plugin with GrapeJS in React but can't get it to work. When I select a piece of text I get an error:

    Uncaught SyntaxError: Unexpected token <
    Uncaught TypeError: Cannot set property 'dir' of undefined
         at Object.f (ckeditor.js:5782)
         at e (ckeditor.js:5816)
         at Array.n (ckeditor.js:5822)
         at q (ckeditor.js:5829)
         at ckeditor.js:5848

This is how I am loading it:
 
    import "ckeditor";
    import pluginCKEditor from "grapesjs-plugin-ckeditor";

then: 

    const editor = grapesjs.init({
        {...}
        plugins: [pluginCKEditor],
        {...}
    })

What am I doing wrong?

**Comment by ColdTuna** [comment]
After doing some searching on this error, some were able to solve it by importing ckeditor using the CDN. So I added the CDN:

    const editor = grapesjs.init({
        container: "#canvas",
        canvas: {
        scripts: [
            "https://cdn.ckeditor.com/ckeditor5/12.4.0/classic/ckeditor.js"
        ]
        }
        ...

This did not solve the issue.

**Comment by HelveticaScenario** [comment]
it means including ckeditor using a script tag in your html, not the scripts field in grapesjs.init. http://cdn.ckeditor.com/
