### ISSUE TITLE
Not able to use colors(TextColor,BGColor) and styles(Font,FontSize) in toolbar

### ISSUE THREAD

**Issue by Spandana8** [artf/grapesjs-plugin-ckeditor#35]
Hi artf,

I am adding colors an styles section in toolbar. I am able to see other sections but not colors and styles in editor. 

`  "gjs-plugin-ckeditor": {
          position: "center",
          options: {
            toolbar: [
              { name: 'styles', items: ['Font', 'FontSize'] },
              { name: 'basicstyles', items: ['Bold', 'Italic', 'Strike', '-', 'RemoveFormat'] },       
              { name: 'links', items: ['Link', 'Unlink'] },
              { name: 'colors', items: ['TextColor', 'BGColor'] }
            ]
          }
        },`

Am I doing anything wrong in the above code. Can you help me out with this? @artf 

Thanks in advance.

**Comment by artf** [comment]
Make sure you include the full version of CKEditor (which include also plugins) and the button support that element (eg. the toolbar renders on `<h1>` is different from one on `<p>`)
