### ISSUE TITLE
Adding a ckeditor plugin within grapesjs

### ISSUE THREAD

**Issue by rafal-olszewski** [artf/grapesjs-plugin-ckeditor#4]
How can I add a plugin for ckeditor, which is initialized from within grapesjs script, and the config is inside grapesjs config.

**Comment by rafal-olszewski** [comment]
I've successfully added a plugin in `ckeditor_root/plugins/myplugin/` but it doesn't suit me, it can't be as a standalone plugin directory, I need it to be in gjs config or so.

**Comment by artf** [comment]
Hi @rafal-olszewski just as explained here http://docs.ckeditor.com/#!/guide/dev_plugins you have to drop your plugin inside `plugins` directory and call it via `extraPlugins` option, in grapesjs:
```js
var editor = grapesjs.init({
      container : '#gjs',
      plugins: ['gjs-plugin-ckeditor'],
      pluginsOpts: {
        'gjs-plugin-ckeditor': {
          options: {
            extraPlugins: 'plugin-name',
          }
        }
      }
  });
```
