### ISSUE TITLE
CKEditor @mentions not working

### ISSUE THREAD

**Issue by anuragpathak21** [artf/grapesjs-plugin-ckeditor#68]
@mentions feature of CKEditor is not working.

**Comment by artf** [comment]
I guess it's about how you configure the CKEditor, not related to the plugin itself

**Comment by anuragpathak21** [comment]
@artf  This issue should not be closed unless confirmed rather than simple guess.

For @mention to work with CKEditor, the CKEditor should be build with the mentions plugin. See the comments from CKEditor and the link below to read about it.

"_This feature was introduced in CKEditor 4.10. It is provided through optional plugins that are not included in the CKEditor 4 presets available from the Download site and need to be added to your custom build with online builder._"

[CKEditor @Mentions](https://ckeditor.com/docs/ckeditor4/latest/features/mentions.html)

**Comment by artf** [comment]
@anuragpathak21 you just need to pass the bundled CKEditor constructor to [`ckeditor` option](https://github.com/GrapesJS/ckeditor#options)
