### ISSUE TITLE
Problems to move a content or drop from canvas if inline editor is enabled

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs-plugin-ckeditor#7]
Hi Art!

I'm having issue with ckeditor, where I cannot move o remove the text component, because ckeditor is over the icons that allow to do this operation, I'm attaching a screencast showing what is happening.

![kapture 2017-09-13 at 11 21 02](https://user-images.githubusercontent.com/97540/30382542-bd31790a-9875-11e7-9ea7-2c3730adafb9.gif)

My suggestions is when the editor is over, the icons could be move for bottom of element select. It will helps a lot.

Thanks

**Comment by artf** [comment]
Ok, for the moment, I'd suggest moving the component toolbar forward
```css
.gjs-toolbar {
     z-index: 15;
}
```

**Comment by rgcarrasqueira** [comment]
Thansk Art! It is working nice!
