### ISSUE TITLE
The specified element mode is not supported on element: "a".

### ISSUE THREAD

**Issue by Chiricato** [artf/grapesjs-plugin-ckeditor#71]
lModuleDefinition:1 Error: The specified element mode is not supported on element: "a".
    at new a (VM5195 ckeditor.js:258:337)
    at CKEDITOR.inline (VM5195 ckeditor.js:344:463)
    at Object.enable (index.ts:147:1)
    at o.eval (universalModuleDefinition:1:1)
    at eval (universalModuleDefinition:1:1)
    at Object.eval [as next] (universalModuleDefinition:1:1)
    at eval (universalModuleDefinition:1:1)
    at new Promise (<anonymous>)
    at Ap (universalModuleDefinition:1:1)
    at o.enable (universalModuleDefinition:1:1) {level: 'error'}

**Comment by ElioNeyt** [comment]
Try to add this: `CKEDITOR.dtd.$editable.a = 1`

**Comment by ElioNeyt** [comment]
Hi,
I have the same error as @Chiricato when I click on the button block containing the href value, it's not editable. I tried adding `CKEDITOR.dtd.$editable.a = 1`
Now i can edit the content once and after that, i can't.

I use grapesjs-mjml and reproduce it in demo. To reproduce: 
- click on the button block, 
- edit it, 
- click outside,
- click on button block again --> can't edit
(sometimes you have to try several times)

I have other issue with button, when i can edit it, the double click open directly link dialog but without text to show and without url, how fix it ?

i have latest release of ckeditor plugin, latest release of grapesjs-mjml.

Thanks for all
PS: sorry for my english, i'm french 😏

**Comment by Chiricato** [comment]
T

> Hi, I have the same error as @Chiricato when I click on the button block containing the href value, it's not editable. I tried adding `CKEDITOR.dtd.$editable.a = 1` Now i can edit the content once and after that, i can't.
> 
> I use grapesjs-mjml and reproduce it in demo. To reproduce:
> 
> * click on the button block,
> * edit it,
> * click outside,
> * click on button block again --> can't edit
>   (sometimes you have to try several times)
> 
> I have other issue with button, when i can edit it, the double click open directly link dialog but without text to show and without url, how fix it ?
> 
> i have latest release of ckeditor plugin, latest release of grapesjs-mjml.
> 
> Thanks for all PS: sorry for my english, i'm french 😏

Thanks. Now work
