### ISSUE TITLE
Ckeditor showing warning popup

### ISSUE THREAD

**Issue by snehlata08** [artf/grapesjs-plugin-ckeditor#85]
When I click on edit text it shows a warning popup to upgrade it to 4.24.0-lts.
![image](https://github.com/GrapesJS/ckeditor/assets/79985986/7ac04c00-e8cb-4a2a-be7f-ae6c812481c5)

When I tried upgrading it to the specified version it gives below error. 
`pluginsOpts: {
          "gjs-blocks-basic": {},
          'grapesjs-preset-webpage': {},
          'grapesjs-plugin-export': {},
          'grapesjs-tabs': {},
          'grapesjs-custom-code': {},
          'grapesjs-parser-postcss': {},
          'grapesjs-style-bg': {},
          'grapesjs-navbar': {},
          'grapesjs-component-countdown': {},
          'grapesjs-tooltip': {},
          'grapesjs-typed': {},
          'grapesjs-blocks-flexbox': {},
          'grapesjs-plugin-forms': {},
          'grapesjs-tui-image-editor': {},
          'grapesjs-style-gradient': {},
          'grapesjs-plugin-ckeditor': {ckeditor: "https://cdn.ckeditor.com/4.24.0-lts/standard-all/ckeditor.js"},
        },`

```
[CKEDITOR]: The license key is missing or invalid.

If you suddenly started to see this message, this may mean you accidentally updated CKEditor 4 to the LTS version (4.23.0 and above). This version of the editor is under commercial terms and requires acquiring an "Extended Support Model" contract - https://ckeditor.com/ckeditor-4-support/

For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#invalid-lts-license-key
```

**Comment by Hunger-King** [comment]
`        
options: {
          versionCheck: false,
        },
`

**Comment by snehlata08** [comment]
> ` options: { versionCheck: false, },`

This works to hide the popup
